# file: docker-compose.yaml
version: "3.9"
services:
  zookeeper:
    image: arm64v8/zookeeper:3.7.2
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  postgres-order:
    image: postgres:16
    environment:
      POSTGRES_DB: ms-order
      POSTGRES_USER: svadmin
      POSTGRES_PASSWORD: Qwerty123
    ports:
      - 5432:5432
    volumes:
      - postgres-order-data:/var/lib/postgresql/data # Persist data in a named volume
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U svadmin" ]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - marketplace-network
  ms-order-api:
    build: .
    image: ms-order-api
    environment:
      DELIVERY_URL: http://ms-delivery-api:8081/ms-delivery
      POSTGRES_URL: jdbc:postgresql://postgres-order:5432/ms-order
      POSTGRES_USER: svadmin
      POSTGRES_PASSWORD: Qwerty123
    ports:
      - 8080:8080
    depends_on:
      - postgres-order
    networks:
      - marketplace-network

volumes:
  postgres-order-data: # Named volume for PostgreSQL data

networks:
  marketplace-network:
    external: true