openapi: 3.0.3
info:
  title: Order Service API
  description: API for managing orders
  version: 1.0.0
servers:
  - url: http://localhost:8080/ms-order
paths:
  /products:
    get:
      summary: Get all products
      tags:
        - Products
      operationId: getProducts
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  /products/{id}:
    get:
      summary: Get a product by ID
      tags:
        - Products
      operationId: getProductById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Product details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found#
  /carts:
    get:
      summary: Get all carts
      tags:
        - Cart
      operationId: getCarts
      responses:
        '200':
          description: A list of carts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cart'
  /carts/by-user/{user_id}:
    get:
      summary: Get the cart for a specific user
      description: Retrieve the cart associated with the specified user ID. If no cart exists, returns a `204 No Content` status.
      tags:
        - Cart
      operationId: getCartsByUser
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The cart associated with the user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '204':
          description: No cart found for the specified user.
  /carts/add-product/{user_id}:
    post:
      summary: Add product to cart
      tags:
        - Cart
      operationId: addProductToCart
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user whose cart the product will be added to.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Product added to the cart successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '400':
          description: User ID and Product must not be null.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: User ID and Product must not be null.
                  timestamp:
                    type: string
                    format: date-time
                    example: "YYYY-MM-DDThh:mm:ss.SSS"
        '404':
          description: Product with ID {id} does not exist.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Product with ID {id} does not exist.
                  timestamp:
                    type: string
                    format: date-time
                    example: "YYYY-MM-DDThh:mm:ss.SSS"
        '500':
          description: Failed to save the cart.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Failed to save the cart.
                  timestamp:
                    type: string
                    format: date-time
                    example: "YYYY-MM-DDThh:mm:ss.SSS"
  /orders:
    get:
      summary: Get all orders
      tags:
        - Order
      operationId: getOrders
      responses:
        '200':
          description: A list of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
    post:
      summary: Create a new order
      tags:
        - Order
      operationId: placeOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cart'
      responses:
        '201':
          description: Order created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Cart must not be null and must have an ID.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: User ID and Product must not be null.
                  timestamp:
                    type: string
                    format: date-time
                    example: "YYYY-MM-DDThh:mm:ss.SSS"
        '404':
          description: Product is currently out of stock.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Your cart contains a product (id = {id}) that is currently out of stock.
                  timestamp:
                    type: string
                    format: date-time
                    example: "YYYY-MM-DDThh:mm:ss.SSS"
        '500':
          description: Failed to save the order.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Failed to save the order.
                  timestamp:
                    type: string
                    format: date-time
                    example: "YYYY-MM-DDThh:mm:ss.SSS"
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        price:
          type: number
          format: double
    Cart:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: string
        createdDate:
          type: string
          format: date-time
        cartProducts:
          type: array
          items:
            $ref: '#/components/schemas/CartProduct'
    CartProduct:
      type: object
      properties:
        id:
          type: integer
          format: int64
        product:
          $ref: '#/components/schemas/Product'
        productQuantity:
          type: integer
          format: int64
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: string
        createdDate:
          type: string
          format: date-time
        orderedProducts:
          type: array
          items:
            $ref: '#/components/schemas/OrderedProduct'
    OrderedProduct:
      type: object
      properties:
        id:
          type: integer
          format: int64
        originalProductId:
          type: integer
          format: int64
        productName:
          type: string
        productPrice:
          type: number
          format: double
        quantity:
          type: integer