openapi: 3.0.3
info:
  title: Order Service API
  description: API for managing orders
  version: 1.0.0
servers:
  - url: http://localhost:8080/ms-order
paths:
  /products:
    get:
      summary: Get all products
      tags:
        - Products
      operationId: getProducts
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  /products/{id}:
    get:
      summary: Get a product by ID
      tags:
        - Products
      operationId: getProductById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Product details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found#
  /carts:
    get:
      summary: Get all carts
      tags:
        - Cart
      operationId: getCarts
      responses:
        '200':
          description: A list of carts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cart'
  /carts/add_product/{user_id}:
    post:
      summary: Add product to cart
      tags:
        - Cart
      operationId: addProductToCart
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Product was added
        '404':
          description: Product not found


components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        price:
          type: number
          format: double
    Cart:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: string
        createdDate:
          type: string
          format: date-time
        cartProducts:
          type: array
          items:
            $ref: '#/components/schemas/CartProduct'
    CartProduct:
      type: object
      properties:
        id:
          type: integer
          format: int64
        product:
          $ref: '#/components/schemas/Product'
        productQuantity:
          type: integer
