name: Update Version on Merge

on:
  pull_request:
    branches:
      - main  # Only trigger when PR is merged into main
    types: [ closed ]

jobs:
  remove-snapshot:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Extract Version Without Snapshot
        id: version
        run: |
          current_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | grep -E '^[0-9]+(\.[0-9]+)*(-SNAPSHOT)?$')
          new_version="${current_version/-SNAPSHOT/}"
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Update Version in pom.xml
        run: |
          mvn versions:set -DnewVersion=${{ env.new_version }} -DgenerateBackupPoms=false

      - name: Commit and Push Version Update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Bump version to $new_version"
          git push origin HEAD:main

      - name: Create and Push Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name="v$new_version"
          git tag -a "$tag_name" -m "Release $new_version"
          git push origin "$tag_name"
